server:
  port: 8000
spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
      - id: member
        uri: http://localhost:8001
        predicates:
          - Path=/member/**
      - id: business
        uri: http://localhost:8002
        predicates:
          - Path=/business/**
      - id: batch
        uri: http://localhost:8003
        predicates:
          - Path=/batch/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
        # 解决options请求被拦截的问题
        add-to-simple-url-handler-mapping: true